job_id: 10847601
title: Gen AI application developer
company: Coditation
location: Pune, IND
work_type: FULL_TIME
company_size: 104 Employees
description: |
  Gen AI application developer

  Pune, India

  About Us

  Coditation was founded by a serial entrepreneur, and a team
  of young talented technologists with a vision of delivering
  high-quality, scalable, and best-in-class products at the
  bleeding edge of technology . We specialize in Machine
  Learning & AI, Data Engineering, Cloud, and Enterprise
  Mobility. We have built a team of ninja architects, data
  scientists, data engineers, and software engineers having
  decades of collective experience of applying emerging
  technologies to build cutting edge software products, and
  are constantly looking to add high-quality and passionate
  engineers.

  What we are looking for

  We are looking for a smart, versatile engineer who can
  seamlessly blend application development with applied AI
  capabilities. You will be responsible for building end-to-
  end web applications and integrating AI-driven features that
  deliver real business value. This is a high-impact role
  where you’ll work on cutting-edge tech, adopt AI-native
  workflows, and move fast without compromising on quality.

  Why join us?

  -Build, ship, and maintain end-to-end agentic applications
  using React/Next.js/Streamlit and Node.js/Python (ExpressJS,
  FastAPI)

  -Work on agent development in the cloud and maintain
  pipelines to ensure seamless delivery.

  -Translate problem statements into working AI-powered
  features.

  -Work with LLM APIs, retrieval-augmented generation (RAG),
  embeddings, and basic fine-tuning.

  -Implement evaluation metrics and guardrails to ensure AI
  output quality and safety.

  -Leverage tools like Cursor (or similar) to enhance
  productivity.

  -Use code generation and inline testing to iterate quickly
  without sacrificing quality.

  -Optimize for latency, cost efficiency, and data security.

  -Write clean, maintainable, and well-instrumented code.

  What you will need

  -3–5 years of experience in application development.

  -Strong proficiency in GenAI frameworks like LangChain,
  LangGraph or similar, React/Next.js/Streamlit, Node.js
  and/or Python and frameworks like ExpressJS or FastAPI

  -Experience integrating AI models (OpenAI, Anthropic,
  Claude, etc.).

  -Familiarity with retrieval techniques, embeddings, and
  fine-tuning workflows.

  -Hands-on experience with cloud environments (AWS/GCP/Azure)
  and CI/CD pipelines.

  -Strong debugging, testing, and instrumentation skills.

  -Understanding of security best practices and performance
  optimization.
industries:
  - Artificial Intelligence
  - Machine Learning
  - Software
posted_date: 2026-08-26
url: "https://builtin.com/job/gen-ai-application-developer/10847601"
source: Built In
